<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Settings_mhs _489u img</name>
   <tag></tag>
   <elementGuidId>91e27fdf-dd57-46b7-b1ac-f549ce56f724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_0_4']/div/div/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mhs._489u.img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mhs _489u img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>68</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>68</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://scontent.fcgk29-1.fna.fbcdn.net/v/t39.2081-6/c0.0.76.76a/p75x75/25618415_324800614672406_2833361887624691712_n.png?_nc_cat=109&amp;ccb=3&amp;_nc_sid=eaa83b&amp;_nc_eui2=AeHCQSfSYtuAVAKfsMoKjlaUikBWwo3KiTaKQFbCjcqJNkLxhNnEpUcYs7qDLTwv0Rg&amp;_nc_ohc=wI4pEbV3w0QAX9kLOpz&amp;_nc_ht=scontent.fcgk29-1.fna&amp;_nc_tp=30&amp;oh=624fa7780fb62699349282c3f44814c8&amp;oe=604AF501</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_4&quot;)/div[@class=&quot;_16l6 _396- _3crb&quot;]/div[@class=&quot;_5p-v&quot;]/div[@class=&quot;_1a_o&quot;]/div[@class=&quot;_1by0&quot;]/div[@class=&quot;_1by1 _1by3&quot;]/div[@class=&quot;_1a_q&quot;]/div[@class=&quot;_1a_r&quot;]/img[@class=&quot;mhs _489u img&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_4']/div/div/div/div/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://scontent.fcgk29-1.fna.fbcdn.net/v/t39.2081-6/c0.0.76.76a/p75x75/25618415_324800614672406_2833361887624691712_n.png?_nc_cat=109&amp;ccb=3&amp;_nc_sid=eaa83b&amp;_nc_eui2=AeHCQSfSYtuAVAKfsMoKjlaUikBWwo3KiTaKQFbCjcqJNkLxhNnEpUcYs7qDLTwv0Rg&amp;_nc_ohc=wI4pEbV3w0QAX9kLOpz&amp;_nc_ht=scontent.fcgk29-1.fna&amp;_nc_tp=30&amp;oh=624fa7780fb62699349282c3f44814c8&amp;oe=604AF501')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
