<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Seperti di KTPPasporSIM (tanpa tanda ba_a71e38</name>
   <tag></tag>
   <elementGuidId>af5a4421-3801-4df6-94c5-5ff4a3dcff99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div/div[2]/form/div[2]/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.popover-overlay-bg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-overlay-bg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;booking-form&quot;]/div[@class=&quot;booking-form-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;card form-card&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;name-field&quot;]/div[@class=&quot;autocomplete-form&quot;]/div[@class=&quot;popover-overlay-bg&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div[2]/form/div[2]/div/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
