<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Tamu_tix tix-plus</name>
   <tag></tag>
   <elementGuidId>9e61ebdf-a97d-46bb-a359-52b8e034b053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hotelGuestRoom']/div[2]/div/div/div[2]/div/div/div[2]/div[3]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.tix.tix-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tix tix-plus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hotelGuestRoom&quot;)/div[@class=&quot;widget-drop-down&quot;]/div[@class=&quot;widget-drop-down-content&quot;]/div[@class=&quot;passenger-cabin-drop-down-container&quot;]/div[@class=&quot;passenger-cabin-drop-down-content-container&quot;]/div[@class=&quot;passenger-cabin-content-list&quot;]/div[@class=&quot;passenger-cabin-item-list&quot;]/div[@class=&quot;widget-passenger-counter-container&quot;]/div[@class=&quot;widget-passenger-logo-container widget-passenger-counter-item&quot;]/i[@class=&quot;tix tix-plus&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hotelGuestRoom']/div[2]/div/div/div[2]/div/div/div[2]/div[3]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/i</value>
   </webElementXpaths>
</WebElementEntity>
